PMSO-169-feat: Create Urls, View, and Unit for Create A New Product
associatedG/pmso-service pull request #26
Opened 2024-08-15 12:01 UTC by ddnguyen99

### Description

Added views and urls for creating a new product.
Added unit tests for create APIs.
### Related Jira(s)

- PMSO-169

### Checklist

- [] I have read and followed the [PR naming convention](https://pulsar.apache.org/contribute/develop-semantic-title/)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### Tests

python manage.py test

2024-08-15 12:32 UTC, LongNgg commented on pmsoService/products/models.py
>      CATEGORY_TYPE_ONE = "Phuy"
Coi lại khúc này có muốn lưu category option trên db là CATEGORY_TYPE_ONE không hay để thung, phuy, co_khi_o_to thôi, t thấy cái thứ 2 lỡ ai nhìn db thì dễ hiểu hơn.

2024-08-15 12:43 UTC, LongNgg commented on pmsoService/products/tests/tests_products.py
> +class TestProductsViews(APITestCase):
Thêm test list product, create existed product, create invalid product,

2024-08-15 12:43 UTC, LongNgg commented on pmsoService/products/models.py
>      CATEGORY_TYPE_ONE = "Phuy"
Coi lại khúc này có muốn lưu category option trên db là CATEGORY_TYPE_ONE không hay để thung, phuy, co_khi_o_to thôi, t thấy cái thứ 2 lỡ ai nhìn db thì dễ hiểu hơn.

2024-08-15 12:43 UTC, LongNgg commented on pmsoService/products/urls.py
> +        "product-orders/<uuid:id>/",
T nhớ bữa @phamhuutriet nói là url cho productorder mình đổi sang /product/orders. Đợi Triết confirm lại.

2024-08-15 17:06 UTC, ddnguyen99 commented on pmsoService/products/models.py
>      CATEGORY_TYPE_ONE = "Phuy"
T đã bỏ hết vào một file Json mà không đụng gì đến code như Triết nói rồi

2024-08-15 17:07 UTC, ddnguyen99 commented on pmsoService/products/tests/tests_products.py
> +class TestProductsViews(APITestCase):
T có create existing product rồi nha

2024-08-18 00:27 UTC, rcs-tringuyen approved these changes

2024-08-18 00:28 UTC, rcs-tringuyen approved these changes

2024-08-18 00:29 UTC, rcs-tringuyen commented
@ddnguyen99 t fix merge conflict ma test bi fail, m double check lai xem sao

2024-08-18 03:15 UTC, phamhuutriet requested changes

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/views.py
> +#Customer View
không cần thiết

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/models.py
> +with open('config/choices_config.json') as choices_config:
nên để trong function riêng trong file riêng, tham khảo ví dụ này https://github.com/associatedG/pmso-service/blob/staging/pmsoService/utils/roles_utils.py#L4

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    TIER_CHOICES = CHOICES["CUSTOMER"]["TIER_CHOICES"]
hạn chế tối đa gọi kiểu này, nên encapsulate trong 1 function để sau này thay đổi chỉ vào đó thay đổi thôi https://github.com/associatedG/pmso-service/blob/staging/pmsoService/utils/roles_utils.py#L4

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    CATEGORY_CHOICES = CHOICES["PRODUCT"]["CATEGORY_CHOICES"]
same as above

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    STATUS_CHOICES = CHOICES["PRODUCT_ORDER"]["STATUS_CHOICES"]
same as above

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_order.py
> +            category="Phuy",
đã tạo config riêng rồi thì không dùng hardcoded string nữa

2024-08-18 03:15 UTC, phamhuutriet commented on pmsoService/products/tests/tests_products.py
> +	category = random.choice(["Phuy", "Thùng", "Cơ Khí Ô Tô"])
same as above, read from a config file instead

2024-08-18 23:02 UTC, rcs-tringuyen commented
@ddnguyen99 Fix merge conflict đi đã

2024-08-19 02:41 UTC, phamhuutriet approved these changes

2024-08-19 02:41 UTC, merged