PMSO-170: Implement Cancel Product Order and Unit Test
associatedG/pmso-service pull request #28
Opened 2024-08-15 19:20 UTC by ddnguyen99

### Description

Add Partial_update in views to cancel Product Order

### Related Jira(s)

- PMSO-170

### Checklist

- [ x] I have read and followed the [PR naming convention](https://pulsar.apache.org/contribute/develop-semantic-title/)
- [x ] My code follows the code style of this project.
- [ x] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### Tests

python manage.py test

2024-08-16 02:01 UTC, rcs-tringuyen commented
@ddnguyen99 Error: https://stackoverflow.com/questions/57406706/direct-assignment-to-the-reverse-side-of-a-related-set-is-prohibited-use-addres
How to fix: Instead of trying to create Product Order using Django models and ORM, you can leverage your API to create order, and then test out the GET functionality.

2024-08-18 00:30 UTC, rcs-tringuyen submitted a review, later dismissed

2024-08-18 00:31 UTC, rcs-tringuyen commented
@LongNgg @phamhuutriet tui bay review gium t do t commit vao roi ko approve dc nua

2024-08-18 03:11 UTC, phamhuutriet requested changes

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_order.py
> -    def test_create_product_order(self):
tại sao xoá test này?

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_order.py
> +        # print(f"Product_oder_id: {self.product_order.id}")
xoá dòng này đi

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_order.py
> +                                     {"status" : "Cancelled"}, format="json")
dùng enum

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +    def test_create_and_get_product_order_with_multiple_product(self):
rename như này không đúng nghĩa, nó chỉ create thôi chứ có get gì đâu

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +    def test_get_product_order(self):
nên split ra 2 test 1 for single 1 for list

2024-08-18 03:11 UTC, phamhuutriet commented on pmsoService/products/views.py
> +    def partial_update(self, request, *args, **kwargs):
không cần thiết, partially update đã được included trong Mixin. Dùng patch thay vì put

2024-08-18 23:02 UTC, rcs-tringuyen commented on .idea/inspectionProfiles/Project_Default.xml
Remove .idea files please @ddnguyen99

2024-08-19 01:27 UTC, rcs-tringuyen approved these changes

2024-08-19 03:46 UTC, phamhuutriet approved these changes

2024-08-19 03:46 UTC, merged