PMSO-96-feat: Single and list of historical product order
associatedG/pmso-service pull request #30
Opened 2024-08-19 14:49 UTC by ddnguyen99

### Description

Add Views, and Unit Test for Single and List of Historical Product Order

### Related Jira(s)

- [Jira ID]

### Checklist

- [ x] I have read and followed the [PR naming convention](https://pulsar.apache.org/contribute/develop-semantic-title/)
- [ x] My code follows the code style of this project.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

### Tests

Include how to test this code change

2024-08-19 16:52 UTC, LongNgg reviewed
Xem mẫu test_customer t đã viết và dùng AI chỉnh clean lại

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +      test_product_1 = Product.objects.create(**mock_product_generator())
sao để test_product_1 vậy. có product_2 không?

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +      product_order = response.data
m có cái MOCK ở trên rồi, lưu variable này chi vậy bro

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/views.py
> +    def get(self, request, *args, **kwargs):
cái này m implement vô serializer luôn t thấy clean hơn

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +        MOCK_PRODUCT_ORDER_THREE = mock_product_order_generator(self.staff.id,
có dùng cái này k?

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +        self.assertEqual(response.status_code, status.HTTP_200_OK)
ở đây nên thêm check order có đúng là order 2 không nữa chứ

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +      MOCK_PRODUCT_ORDER = mock_product_order_generator(self.staff.id,
sao không tạo product order có status complete hay cancelled sẵn luôn ở đây

2024-08-19 16:52 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +        MOCK_PRODUCT_ORDER_ONE = mock_product_order_generator(self.staff.id,
same as above, generate để status luôn

2024-08-19 17:07 UTC, LongNgg commented on pmsoService/products/tests/tests_product_orders.py
> +        MOCK_PRODUCT_ORDER_THREE = mock_product_order_generator(self.staff.id,
mấy cái mock này trong @classmethod setUp có sẵn 1 cái product order rồi, m cần thì patch lại hoặc tạo 1 cái mock_2 để test list đồ thôi.

2024-08-20 12:23 UTC, phamhuutriet requested changes

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/views.py
> +        if instance.status in ['Cancelled', 'Completed']:
đã có enum rồi thì dùng enum, đừng dùng hardcoded string

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/views.py
> +            queryset = ProductOrder.objects.all().filter(status__in=['Cancelled', 'Completed'])
nên có 1 variable riêng cho cái list of status này 
`historical_status = ['Cancelled', 'Completed']`, hạn chế tối đa lặp đi lặp lại

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +    def test_get_historical_product_order_with_single_product(self):
nên là `test_get_single_historical_product`

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +      response = self.client.patch(reverse("product_order_detail", kwargs={"id": product_order['id']}),
thay vì post rồi patch như này thì sao không modify `mock_product_order_generator` để accept status as an argument rồi tạo mock data với status mong muốn. Lúc này post 1 lần là được rồi

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +        response = self.client.post(reverse("product_order_list_create"), MOCK_PRODUCT_ORDER_TWO, format='json')
nếu cần tạo nhiều product order trên database quá thì viết riêng 1 function để tạo product order luôn, trong đó có tạo mock data + post lên server. Như vậy code đỡ duplicate hơn

2024-08-20 12:23 UTC, phamhuutriet commented on pmsoService/products/tests/tests_product_orders.py
> +    def test_get_a_list_of_historical_product_order_with_single_product(self):
`with single product` là sao? Trước khi viết test cần phải xác định rõ muốn test gì. Ở đây muốn test đơn thuần là get list of historical product orders thì liên quan gì đến single hay multiple product đâu

2024-08-20 16:16 UTC, ddnguyen99 commented
T tạm thời close cái PR này. Tại t vs Long mới kiếm ra cách làm filter bằng django_filter nhanh gọn lắm

2024-08-20 16:16 UTC, closed without merging