Pmso 41 product orders
associatedG/pmso-service pull request #6
Opened 2024-08-08 17:44 UTC by ddnguyen99

### Description

Please include a summary of the changes and the related issue(s) this PR addresses.

### Related Jira(s)

- [Jira ID]

### Checklist

- [ ] I have read and followed the [PR naming convention](https://pulsar.apache.org/contribute/develop-semantic-title/)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### Tests

Include how to test this code change

2024-08-08 20:41 UTC, rcs-tringuyen commented on pmsoService/products/migrations/0001_initial.py
> +                ('status', models.CharField(max_length=50)),
Có nên để choices thay vì generic char field ở đây không? https://docs.djangoproject.com/en/5.1/ref/models/fields/
@phamhuutriet

2024-08-08 21:00 UTC, rcs-tringuyen requested changes

2024-08-08 21:00 UTC, rcs-tringuyen commented on pmsoService/products/views.py
> +class ProductOrderCreateAPIView(generics.CreateAPIView):
Maybe nên xài `APIView` thay vì `generics.CreateAPIView` đọc PR comment của t cho example nha

2024-08-08 21:03 UTC, rcs-tringuyen commented
@phamhuutriet:
- Có nên enable authentication không? Hay là m muốn làm sau? Phải xác định authentication scheme mình muốn sử dụng nữa.
- **T nghĩ là nên setup `drf_yasg` luôn**

2024-08-08 21:06 UTC, rcs-tringuyen commented
Review suggestion của t trong Discord về View design nhé @ddnguyen99 @LongNgg @phamhuutriet

2024-08-09 02:16 UTC, phamhuutriet commented on pmsoService/products/migrations/0003_alter_product_quantity_alter_productorder_isurgent_and_more.py
> +class Migration(migrations.Migration):
T nghĩ k nên có nhiều file migration trong 1 PR, nếu có thay đổi gì ở model thì m có thể xoá cái migration file trước đó

2024-08-09 02:20 UTC, phamhuutriet commented on pmsoService/products/models.py
> +        choices=PRIORITY_CHOICES,
isUrgent là boolean theo doc thì không pass choices vào được

2024-08-09 02:36 UTC, phamhuutriet reviewed
Thiếu update url của product order trong root url của project, [example](https://github.com/associatedG/pmso-service/blob/main/pmsoService/pmsoService/urls.py#L24)

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    products = models.ManyToManyField(
Mình đã dùng relationship table ProductOrderProduct ở dưới rồi thì không cần field này nữa

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/models.py
> +class ProductOrder(models.Model):
Thiếu `saleStaffId` `logisticStaffId` với `delivererId`

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    price = models.DecimalField(max_digits=10, decimal_places=2)
Tiền việt sao có decimal được, trong [database design](https://lucid.app/lucidchart/3482dab7-33f0-47c5-b252-759a3b3f0bf1/edit?invitationId=inv_018c9a52-3937-464f-a35f-c31154740808&page=0_0#) field này là int

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    category = models.CharField(max_length=255)
nên dùng [choices](https://docs.djangoproject.com/en/5.1/ref/models/fields/#choices)

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/models.py
> +    name = models.CharField(max_length=255)
nên có option unique cho `name`

2024-08-09 02:36 UTC, phamhuutriet commented on pmsoService/products/views.py
> +class ProductOrderCreateAPIView(generics.CreateAPIView):
nên dùng list create view luôn, [example](https://github.com/associatedG/pmso-service/blob/main/pmsoService/account/views.py#L12)

2024-08-09 03:51 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +        choices=PRIORITY_CHOICES,
Done nha

2024-08-09 06:37 UTC, ddnguyen99 commented on pmsoService/products/migrations/0003_alter_product_quantity_alter_productorder_isurgent_and_more.py
> +class Migration(migrations.Migration):
Cái này giờ sửa sao. Hay bắt đầu từ thằng sau thì nên chia nhỏ ra

2024-08-09 06:40 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +    createdAt = models.DateTimeField(auto_now_add=True)
Done

2024-08-09 06:40 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +    isUrgent = models.BooleanField(
T để tiếng việt luôn nha

2024-08-09 06:40 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +    status = models.CharField(max_length=50)
Done

2024-08-09 06:41 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +        choices=PRIORITY_CHOICES,
Done nha. Cái status Urgent or Not Urgent sẽ có một cái def ở trong Serializer xử lý nó. Giờ để thành Boolean

2024-08-09 11:05 UTC, ddnguyen99 commented on pmsoService/products/migrations/0003_alter_product_quantity_alter_productorder_isurgent_and_more.py
> +class Migration(migrations.Migration):
T đã hiểu và solve

2024-08-09 11:32 UTC, LongNgg commented on pmsoService/products/models.py
> +    isUrgent = models.BooleanField(default=False)
Chỉnh lại naming convention theo snake_case cho model nhé

2024-08-09 11:32 UTC, LongNgg commented on pmsoService/products/views.py
> +class ProductOrderCreateAPIView(generics.ListCreateAPIView):
API là ListCreate thì tên class cũng để ListCreate nhé

2024-08-09 11:44 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +    isUrgent = models.BooleanField(default=False)
Boolean không dùng choice được theo doc của Django

2024-08-09 11:49 UTC, ddnguyen99 commented on pmsoService/products/views.py
> +class ProductOrderCreateAPIView(generics.ListCreateAPIView):
Done nha

2024-08-09 11:49 UTC, ddnguyen99 commented on pmsoService/products/models.py
> +    category = models.CharField(max_length=255)
Done nha

2024-08-09 11:54 UTC, LongNgg commented on pmsoService/products/models.py
> +    isUrgent = models.BooleanField(default=False)
sao ở đây cần dùng Boolean m, t thấy CharField choices là oke rồi mà, mình muốn dùng gì đặc biệt với cái này á

2024-08-09 12:08 UTC, LongNgg commented on pmsoService/products/models.py
> +    dueDate = models.DateField()
Chỉnh dưới serializer luôn nhé

2024-08-09 12:08 UTC, LongNgg commented on pmsoService/products/urls.py
> +         name='product_detail'),
[url pattern naming convention](https://www.django-rest-framework.org/tutorial/5-relationships-and-hyperlinked-apis/#making-sure-our-url-patterns-are-named)

2024-08-09 15:35 UTC, LongNgg submitted a review, later dismissed
oke

2024-08-09 16:11 UTC, rcs-tringuyen submitted a review, later dismissed
Approved. But change url path from productorders to product-orders

2024-08-09 16:47 UTC, rcs-tringuyen approved these changes

2024-08-09 16:48 UTC, LongNgg approved these changes
oke

2024-08-09 16:49 UTC, merged